
skillMetadata:
  sections:
    - name: Netatmo account
      fields:
        - type: label
          label: The user you use to log into https://www.netatmo.com/

        - name: username
          type: text
          label: Email
          value: ""
          placeholder: Netatmo login email
        - name: password
          type: password
          label: Password
          value: ""

    - name: Netatmo App
      fields:
        - type: label
          label: If you haven't created your app yet, create one in a minute here (https://dev.netatmo.com/guideline/)

        - name: client_id
          type: text
          label: Client ID
          value: ""
          placeholder: your Netatmo App ID code
        - name: client_secret
          type: password
          label: Client Secret
          value: ""
          placeholder: your Netatmo App Secret code


